import turtle
import time 
pen = turtle.Turtle() 

def legOrArm(x, y, length, width):
    #pen.speed(1)
    pen.fillcolor('black')
    pen.begin_fill()
    pen.setheading(270)
    pen.goto(x, y)
    pen.down()
    for i in range(2):
        pen.forward(width)
        pen.left(90)
        pen.forward(length)
        pen.left(90)
    pen.left(135)
    pen.forward(width)
    pen.right(45)
    pen.forward(length)
    pen.right(135)
    pen.forward(width)
    pen.end_fill()
    pen.up()
    pen.right(180)
    pen.forward(width)
    pen.right(135)
    pen.down()
    pen.begin_fill()
    pen.forward(width)
    pen.right(45)
    pen.forward(width)
    pen.end_fill()
    pen.up()

'''def legOrArm(x, y, size):
    pen.setheading(270)
    pen.goto(x, y)
    pen.down()
    for i in range(2):
        pen.forward(50)
        pen.left(90)
        pen.forward(size)
        pen.left(90)
        pen.left(135)
    pen.forward(v)
    pen.right(45)
    pen.forward(v)
    pen.right(135)
    pen.forward(v)
    pen.up()
    pen.right(180)
    pen.forward(v)
    pen.right(135)
    pen.down()
    pen.forward(size)
    pen.right(45)
    pen.forward(v)
    pen.up()'''

def bodyOrHead(x, y, l, width):
    pen.setheading(270)
    pen.goto(x, y)
    pen.down()
    for i in range(2):
        pen.forward(width)
        pen.left(90)
        pen.forward(l)
        pen.left(90)
    pen.left(135)
    pen.forward(l)
    pen.right(45)
    pen.forward(l)
    pen.right(135)
    pen.forward(l)
    pen.up()
    pen.right(180)
    pen.forward(l)
    pen.right(135)
    pen.down()
    pen.forward(width)
    pen.right(45)
    pen.forward(l)
    pen.up()

pen.up()
bodyOrHead(0, 70, 45, 70)
legOrArm(0, -2, 20, 45)
legOrArm(25, -2, 20, 45)
legOrArm(-22, 70, 20, 45)
legOrArm(47, 70, 20, 45)
bodyOrHead(0, 118, 45, 45)

#22+50+2

time.sleep(5)
